# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 187)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ChatResponderC = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatResponderC.sizePolicy().hasHeightForWidth())
        self.ChatResponderC.setSizePolicy(sizePolicy)
        self.ChatResponderC.setText("")
        self.ChatResponderC.setObjectName("ChatResponderC")
        self.gridLayout.addWidget(self.ChatResponderC, 0, 0, 1, 1)
        self.ChatResponderB = QtWidgets.QPushButton(self.centralwidget)
        self.ChatResponderB.setObjectName("ChatResponderB")
        self.gridLayout.addWidget(self.ChatResponderB, 0, 1, 1, 1)
        self.AutoClickerC = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AutoClickerC.sizePolicy().hasHeightForWidth())
        self.AutoClickerC.setSizePolicy(sizePolicy)
        self.AutoClickerC.setText("")
        self.AutoClickerC.setObjectName("AutoClickerC")
        self.gridLayout.addWidget(self.AutoClickerC, 1, 0, 1, 1)
        self.AutoClickerB = QtWidgets.QPushButton(self.centralwidget)
        self.AutoClickerB.setObjectName("AutoClickerB")
        self.gridLayout.addWidget(self.AutoClickerB, 1, 1, 1, 1)
        self.AutoClickerO = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AutoClickerO.sizePolicy().hasHeightForWidth())
        self.AutoClickerO.setSizePolicy(sizePolicy)
        self.AutoClickerO.setMaximumSize(QtCore.QSize(34, 16777215))
        self.AutoClickerO.setObjectName("AutoClickerO")
        self.gridLayout.addWidget(self.AutoClickerO, 1, 2, 1, 1)
        self.AutoBowC = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AutoBowC.sizePolicy().hasHeightForWidth())
        self.AutoBowC.setSizePolicy(sizePolicy)
        self.AutoBowC.setText("")
        self.AutoBowC.setObjectName("AutoBowC")
        self.gridLayout.addWidget(self.AutoBowC, 2, 0, 1, 1)
        self.AutoBowB = QtWidgets.QPushButton(self.centralwidget)
        self.AutoBowB.setObjectName("AutoBowB")
        self.gridLayout.addWidget(self.AutoBowB, 2, 1, 1, 1)
        self.AutoBowO = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AutoBowO.sizePolicy().hasHeightForWidth())
        self.AutoBowO.setSizePolicy(sizePolicy)
        self.AutoBowO.setMaximumSize(QtCore.QSize(34, 16777215))
        self.AutoBowO.setIconSize(QtCore.QSize(0, 0))
        self.AutoBowO.setObjectName("AutoBowO")
        self.gridLayout.addWidget(self.AutoBowO, 2, 2, 1, 1)
        self.ChatResponderO = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatResponderO.sizePolicy().hasHeightForWidth())
        self.ChatResponderO.setSizePolicy(sizePolicy)
        self.ChatResponderO.setMaximumSize(QtCore.QSize(34, 16777215))
        self.ChatResponderO.setObjectName("ChatResponderO")
        self.gridLayout.addWidget(self.ChatResponderO, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(385, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCheat"))
        self.ChatResponderB.setText(_translate("MainWindow", "Chat Responder"))
        self.AutoClickerB.setText(_translate("MainWindow", "AutoClicker"))
        self.AutoClickerO.setText(_translate("MainWindow", "..."))
        self.AutoBowB.setText(_translate("MainWindow", "AutoBow"))
        self.AutoBowO.setText(_translate("MainWindow", "..."))
        self.ChatResponderO.setText(_translate("MainWindow", "...."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
