FROM ubuntu:18.04

MAINTAINER eyllanesc <e.yllanescucho@gmail.com>

RUN apt-get update && \
    apt-get autoclean

RUN apt-get update && apt-get install \
  -y --no-install-recommends \
  python-qt4 \
  python3-pyqt4 \
  python3-pyqt5 \
  python-pyqt5 \
  python-pyside \
  python3-pyside