# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadInput_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoadInput(object):
    def setupUi(self, LoadInput):
        LoadInput.setObjectName("LoadInput")
        LoadInput.resize(566, 397)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadInput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Load_Input_GroupBox = QtWidgets.QGroupBox(LoadInput)
        self.Load_Input_GroupBox.setObjectName("Load_Input_GroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Load_Input_GroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Load_Input_Top_Userinputs_hoz = QtWidgets.QHBoxLayout()
        self.Load_Input_Top_Userinputs_hoz.setObjectName("Load_Input_Top_Userinputs_hoz")
        self.Load_Input_Text_Load_Name = QtWidgets.QLabel(self.Load_Input_GroupBox)
        self.Load_Input_Text_Load_Name.setObjectName("Load_Input_Text_Load_Name")
        self.Load_Input_Top_Userinputs_hoz.addWidget(self.Load_Input_Text_Load_Name)
        self.Load_Input_UserInput_Load_Name = QtWidgets.QLineEdit(self.Load_Input_GroupBox)
        self.Load_Input_UserInput_Load_Name.setObjectName("Load_Input_UserInput_Load_Name")
        self.Load_Input_Top_Userinputs_hoz.addWidget(self.Load_Input_UserInput_Load_Name)
        self.Load_Input_Text_Voltage = QtWidgets.QLabel(self.Load_Input_GroupBox)
        self.Load_Input_Text_Voltage.setObjectName("Load_Input_Text_Voltage")
        self.Load_Input_Top_Userinputs_hoz.addWidget(self.Load_Input_Text_Voltage)
        self.Load_Input_UserInput_Voltage = QtWidgets.QLineEdit(self.Load_Input_GroupBox)
        self.Load_Input_UserInput_Voltage.setObjectName("Load_Input_UserInput_Voltage")
        self.Load_Input_Top_Userinputs_hoz.addWidget(self.Load_Input_UserInput_Voltage)
        self.Load_Input_Text_Utility = QtWidgets.QLabel(self.Load_Input_GroupBox)
        self.Load_Input_Text_Utility.setObjectName("Load_Input_Text_Utility")
        self.Load_Input_Top_Userinputs_hoz.addWidget(self.Load_Input_Text_Utility)
        self.Load_Input_ComboBox_Utility = QtWidgets.QComboBox(self.Load_Input_GroupBox)
        self.Load_Input_ComboBox_Utility.setObjectName("Load_Input_ComboBox_Utility")
        self.Load_Input_Top_Userinputs_hoz.addWidget(self.Load_Input_ComboBox_Utility)
        self.verticalLayout_7.addLayout(self.Load_Input_Top_Userinputs_hoz)
        self.Load_Input_Top_UserInputs2_hoz = QtWidgets.QHBoxLayout()
        self.Load_Input_Top_UserInputs2_hoz.setObjectName("Load_Input_Top_UserInputs2_hoz")
        self.Load_Input_Text_Wattage = QtWidgets.QLabel(self.Load_Input_GroupBox)
        self.Load_Input_Text_Wattage.setObjectName("Load_Input_Text_Wattage")
        self.Load_Input_Top_UserInputs2_hoz.addWidget(self.Load_Input_Text_Wattage)
        self.Load_Input_UserInput_Wattage = QtWidgets.QLineEdit(self.Load_Input_GroupBox)
        self.Load_Input_UserInput_Wattage.setObjectName("Load_Input_UserInput_Wattage")
        self.Load_Input_Top_UserInputs2_hoz.addWidget(self.Load_Input_UserInput_Wattage)
        self.Load_Input_Text_Power_Factor = QtWidgets.QLabel(self.Load_Input_GroupBox)
        self.Load_Input_Text_Power_Factor.setObjectName("Load_Input_Text_Power_Factor")
        self.Load_Input_Top_UserInputs2_hoz.addWidget(self.Load_Input_Text_Power_Factor)
        self.Load_Input_UserInput_PowerFactor = QtWidgets.QLineEdit(self.Load_Input_GroupBox)
        self.Load_Input_UserInput_PowerFactor.setObjectName("Load_Input_UserInput_PowerFactor")
        self.Load_Input_Top_UserInputs2_hoz.addWidget(self.Load_Input_UserInput_PowerFactor)
        self.Load_Input_Text_VA = QtWidgets.QLabel(self.Load_Input_GroupBox)
        self.Load_Input_Text_VA.setObjectName("Load_Input_Text_VA")
        self.Load_Input_Top_UserInputs2_hoz.addWidget(self.Load_Input_Text_VA)
        self.Load_Input_Text_VALUE = QtWidgets.QLabel(self.Load_Input_GroupBox)
        self.Load_Input_Text_VALUE.setObjectName("Load_Input_Text_VALUE")
        self.Load_Input_Top_UserInputs2_hoz.addWidget(self.Load_Input_Text_VALUE)
        self.verticalLayout_7.addLayout(self.Load_Input_Top_UserInputs2_hoz)
        self.Load_Input_Top_buttons_hoz = QtWidgets.QHBoxLayout()
        self.Load_Input_Top_buttons_hoz.setObjectName("Load_Input_Top_buttons_hoz")
        self.Load_Input_Button_Add_To_Window = QtWidgets.QPushButton(self.Load_Input_GroupBox)
        self.Load_Input_Button_Add_To_Window.setObjectName("Load_Input_Button_Add_To_Window")
        self.Load_Input_Top_buttons_hoz.addWidget(self.Load_Input_Button_Add_To_Window)
        self.Load_Input_Button_Modify_Load = QtWidgets.QPushButton(self.Load_Input_GroupBox)
        self.Load_Input_Button_Modify_Load.setObjectName("Load_Input_Button_Modify_Load")
        self.Load_Input_Top_buttons_hoz.addWidget(self.Load_Input_Button_Modify_Load)
        self.Load_Input_Button_Remove_Load = QtWidgets.QPushButton(self.Load_Input_GroupBox)
        self.Load_Input_Button_Remove_Load.setObjectName("Load_Input_Button_Remove_Load")
        self.Load_Input_Top_buttons_hoz.addWidget(self.Load_Input_Button_Remove_Load)
        self.verticalLayout_7.addLayout(self.Load_Input_Top_buttons_hoz)
        self.verticalLayout.addWidget(self.Load_Input_GroupBox)
        self.Load_Input_Table = QtWidgets.QTableView(LoadInput)
        self.Load_Input_Table.setObjectName("Load_Input_Table")
        self.verticalLayout.addWidget(self.Load_Input_Table)
        self.Load_Input_Button_Send = QtWidgets.QPushButton(LoadInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Load_Input_Button_Send.sizePolicy().hasHeightForWidth())
        self.Load_Input_Button_Send.setSizePolicy(sizePolicy)
        self.Load_Input_Button_Send.setObjectName("Load_Input_Button_Send")
        self.verticalLayout.addWidget(self.Load_Input_Button_Send)
        self.Load_Input_Button_Close = QtWidgets.QPushButton(LoadInput)
        self.Load_Input_Button_Close.setObjectName("Load_Input_Button_Close")
        self.verticalLayout.addWidget(self.Load_Input_Button_Close)

        self.retranslateUi(LoadInput)
        QtCore.QMetaObject.connectSlotsByName(LoadInput)

    def retranslateUi(self, LoadInput):
        _translate = QtCore.QCoreApplication.translate
        LoadInput.setWindowTitle(_translate("LoadInput", "Form"))
        self.Load_Input_GroupBox.setTitle(_translate("LoadInput", "Load Input"))
        self.Load_Input_Text_Load_Name.setText(_translate("LoadInput", "Load Name:"))
        self.Load_Input_Text_Voltage.setText(_translate("LoadInput", "Voltage:"))
        self.Load_Input_Text_Utility.setText(_translate("LoadInput", "Utility:"))
        self.Load_Input_Text_Wattage.setText(_translate("LoadInput", "Wattage:"))
        self.Load_Input_Text_Power_Factor.setText(_translate("LoadInput", "Power Factor:"))
        self.Load_Input_Text_VA.setText(_translate("LoadInput", "VA:"))
        self.Load_Input_Text_VALUE.setText(_translate("LoadInput", "0"))
        self.Load_Input_Button_Add_To_Window.setText(_translate("LoadInput", "Add To Window"))
        self.Load_Input_Button_Modify_Load.setText(_translate("LoadInput", "Modify Load"))
        self.Load_Input_Button_Remove_Load.setText(_translate("LoadInput", "Remove Load"))
        self.Load_Input_Button_Send.setText(_translate("LoadInput", "Send"))
        self.Load_Input_Button_Close.setText(_translate("LoadInput", "Close without sending"))

