# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/remotecontrol.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoteControlClass(object):
    def setupUi(self, RemoteControlClass):
        RemoteControlClass.setObjectName("RemoteControlClass")
        RemoteControlClass.resize(344, 364)
        self.centralWidget = QtWidgets.QWidget(RemoteControlClass)
        self.centralWidget.setObjectName("centralWidget")
        self.gridlayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridlayout.setContentsMargins(11, 11, 11, 11)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.startUrlLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.startUrlLineEdit.setObjectName("startUrlLineEdit")
        self.gridlayout.addWidget(self.startUrlLineEdit, 0, 1, 1, 2)
        self.launchButton = QtWidgets.QPushButton(self.centralWidget)
        self.launchButton.setObjectName("launchButton")
        self.gridlayout.addWidget(self.launchButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(113, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridlayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.actionGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.actionGroupBox.setEnabled(False)
        self.actionGroupBox.setObjectName("actionGroupBox")
        self.gridlayout1 = QtWidgets.QGridLayout(self.actionGroupBox)
        self.gridlayout1.setContentsMargins(11, 11, 11, 11)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.label_2 = QtWidgets.QLabel(self.actionGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridlayout1.addWidget(self.label_2, 0, 0, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.indexLineEdit = QtWidgets.QLineEdit(self.actionGroupBox)
        self.indexLineEdit.setObjectName("indexLineEdit")
        self.hboxlayout.addWidget(self.indexLineEdit)
        self.indexButton = QtWidgets.QToolButton(self.actionGroupBox)
        self.indexButton.setText("")
        icon = QtGui.QIcon()
        icon.addFile(":/remotecontrol/enter.png")
        self.indexButton.setIcon(icon)
        self.indexButton.setObjectName("indexButton")
        self.hboxlayout.addWidget(self.indexButton)
        self.gridlayout1.addLayout(self.hboxlayout, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.actionGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridlayout1.addWidget(self.label_4, 1, 0, 1, 1)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setSpacing(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.identifierLineEdit = QtWidgets.QLineEdit(self.actionGroupBox)
        self.identifierLineEdit.setObjectName("identifierLineEdit")
        self.hboxlayout1.addWidget(self.identifierLineEdit)
        self.identifierButton = QtWidgets.QToolButton(self.actionGroupBox)
        self.identifierButton.setText("")
        self.identifierButton.setIcon(icon)
        self.identifierButton.setObjectName("identifierButton")
        self.hboxlayout1.addWidget(self.identifierButton)
        self.gridlayout1.addLayout(self.hboxlayout1, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.actionGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridlayout1.addWidget(self.label_3, 2, 0, 1, 1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setSpacing(0)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.urlLineEdit = QtWidgets.QLineEdit(self.actionGroupBox)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.hboxlayout2.addWidget(self.urlLineEdit)
        self.urlButton = QtWidgets.QToolButton(self.actionGroupBox)
        self.urlButton.setText("")
        self.urlButton.setIcon(icon)
        self.urlButton.setObjectName("urlButton")
        self.hboxlayout2.addWidget(self.urlButton)
        self.gridlayout1.addLayout(self.hboxlayout2, 2, 1, 1, 2)
        self.syncContentsButton = QtWidgets.QPushButton(self.actionGroupBox)
        self.syncContentsButton.setObjectName("syncContentsButton")
        self.gridlayout1.addWidget(self.syncContentsButton, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(81, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 3, 2, 1, 1)
        self.contentsCheckBox = QtWidgets.QCheckBox(self.actionGroupBox)
        self.contentsCheckBox.setObjectName("contentsCheckBox")
        self.gridlayout1.addWidget(self.contentsCheckBox, 4, 0, 1, 3)
        self.indexCheckBox = QtWidgets.QCheckBox(self.actionGroupBox)
        self.indexCheckBox.setObjectName("indexCheckBox")
        self.gridlayout1.addWidget(self.indexCheckBox, 5, 0, 1, 1)
        self.bookmarksCheckBox = QtWidgets.QCheckBox(self.actionGroupBox)
        self.bookmarksCheckBox.setObjectName("bookmarksCheckBox")
        self.gridlayout1.addWidget(self.bookmarksCheckBox, 6, 0, 1, 3)
        self.gridlayout.addWidget(self.actionGroupBox, 3, 0, 1, 3)
        RemoteControlClass.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(RemoteControlClass)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 344, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        RemoteControlClass.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(RemoteControlClass)
        self.statusBar.setObjectName("statusBar")
        RemoteControlClass.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(RemoteControlClass)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(RemoteControlClass)
        QtCore.QMetaObject.connectSlotsByName(RemoteControlClass)

    def retranslateUi(self, RemoteControlClass):
        _translate = QtCore.QCoreApplication.translate
        RemoteControlClass.setWindowTitle(_translate("RemoteControlClass", "RemoteControl"))
        self.label.setText(_translate("RemoteControlClass", "Start URL:"))
        self.launchButton.setText(_translate("RemoteControlClass", "Launch Qt HelpViewer"))
        self.actionGroupBox.setTitle(_translate("RemoteControlClass", "Actions"))
        self.label_2.setText(_translate("RemoteControlClass", "Search in Index:"))
        self.label_4.setText(_translate("RemoteControlClass", "Identifier:"))
        self.label_3.setText(_translate("RemoteControlClass", "Show URL:"))
        self.syncContentsButton.setText(_translate("RemoteControlClass", "Sync Contents"))
        self.contentsCheckBox.setText(_translate("RemoteControlClass", "Show Contents"))
        self.indexCheckBox.setText(_translate("RemoteControlClass", "Show Index"))
        self.bookmarksCheckBox.setText(_translate("RemoteControlClass", "Show Bookmarks"))
        self.menuFile.setTitle(_translate("RemoteControlClass", "File"))
        self.actionQuit.setText(_translate("RemoteControlClass", "Quit"))


import remotecontrol_rc
