#ifndef INTERFACEPLUGIN_GLOBAL_H
#define INTERFACEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERFACEPLUGIN_LIBRARY)
#define INTERFACEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define INTERFACEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERFACEPLUGIN_GLOBAL_H
