# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splitter_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(800, 600)
        self.centralwidget = QtGui.QWidget(frmMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imgView = QtGui.QGraphicsView(self.centralwidget)
        self.imgView.setGeometry(QtCore.QRect(0, 0, 571, 491))
        self.imgView.setObjectName(_fromUtf8("imgView"))
        self.grpControls = QtGui.QGroupBox(self.centralwidget)
        self.grpControls.setGeometry(QtCore.QRect(570, 0, 221, 461))
        self.grpControls.setObjectName(_fromUtf8("grpControls"))
        self.lblScale = QtGui.QLabel(self.grpControls)
        self.lblScale.setGeometry(QtCore.QRect(0, 90, 131, 17))
        self.lblScale.setObjectName(_fromUtf8("lblScale"))
        self.txtScaleWidth = QtGui.QLineEdit(self.grpControls)
        self.txtScaleWidth.setGeometry(QtCore.QRect(0, 110, 41, 27))
        self.txtScaleWidth.setObjectName(_fromUtf8("txtScaleWidth"))
        self.btnReset = QtGui.QPushButton(self.grpControls)
        self.btnReset.setGeometry(QtCore.QRect(110, 380, 99, 27))
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.lblWidthLabel = QtGui.QLabel(self.grpControls)
        self.lblWidthLabel.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.lblWidthLabel.setObjectName(_fromUtf8("lblWidthLabel"))
        self.lblHeightLabel = QtGui.QLabel(self.grpControls)
        self.lblHeightLabel.setGeometry(QtCore.QRect(120, 30, 51, 17))
        self.lblHeightLabel.setObjectName(_fromUtf8("lblHeightLabel"))
        self.lblSizeXLabel = QtGui.QLabel(self.grpControls)
        self.lblSizeXLabel.setGeometry(QtCore.QRect(80, 30, 16, 17))
        self.lblSizeXLabel.setObjectName(_fromUtf8("lblSizeXLabel"))
        self.lblWidth = QtGui.QLabel(self.grpControls)
        self.lblWidth.setGeometry(QtCore.QRect(10, 50, 51, 17))
        self.lblWidth.setText(_fromUtf8(""))
        self.lblWidth.setObjectName(_fromUtf8("lblWidth"))
        self.lblSizeX = QtGui.QLabel(self.grpControls)
        self.lblSizeX.setGeometry(QtCore.QRect(80, 50, 16, 17))
        self.lblSizeX.setObjectName(_fromUtf8("lblSizeX"))
        self.lblHeight = QtGui.QLabel(self.grpControls)
        self.lblHeight.setGeometry(QtCore.QRect(120, 50, 51, 17))
        self.lblHeight.setText(_fromUtf8(""))
        self.lblHeight.setObjectName(_fromUtf8("lblHeight"))
        self.lblVerticalLabel = QtGui.QLabel(self.grpControls)
        self.lblVerticalLabel.setGeometry(QtCore.QRect(0, 170, 68, 17))
        self.lblVerticalLabel.setObjectName(_fromUtf8("lblVerticalLabel"))
        self.lblSegmentXLabel = QtGui.QLabel(self.grpControls)
        self.lblSegmentXLabel.setGeometry(QtCore.QRect(70, 170, 21, 17))
        self.lblSegmentXLabel.setObjectName(_fromUtf8("lblSegmentXLabel"))
        self.lblHorizontalLabel = QtGui.QLabel(self.grpControls)
        self.lblHorizontalLabel.setGeometry(QtCore.QRect(100, 170, 68, 17))
        self.lblHorizontalLabel.setObjectName(_fromUtf8("lblHorizontalLabel"))
        self.lblSegmentsLabel = QtGui.QLabel(self.grpControls)
        self.lblSegmentsLabel.setGeometry(QtCore.QRect(0, 140, 68, 17))
        self.lblSegmentsLabel.setObjectName(_fromUtf8("lblSegmentsLabel"))
        self.txtVertical = QtGui.QLineEdit(self.grpControls)
        self.txtVertical.setGeometry(QtCore.QRect(0, 190, 71, 27))
        self.txtVertical.setObjectName(_fromUtf8("txtVertical"))
        self.lblVertical = QtGui.QLabel(self.grpControls)
        self.lblVertical.setGeometry(QtCore.QRect(90, 190, 68, 17))
        self.lblVertical.setObjectName(_fromUtf8("lblVertical"))
        self.txtHorizontal = QtGui.QLineEdit(self.grpControls)
        self.txtHorizontal.setGeometry(QtCore.QRect(0, 230, 71, 27))
        self.txtHorizontal.setObjectName(_fromUtf8("txtHorizontal"))
        self.lblHorizontal = QtGui.QLabel(self.grpControls)
        self.lblHorizontal.setGeometry(QtCore.QRect(90, 230, 68, 17))
        self.lblHorizontal.setObjectName(_fromUtf8("lblHorizontal"))
        self.lblScaleX = QtGui.QLabel(self.grpControls)
        self.lblScaleX.setGeometry(QtCore.QRect(50, 120, 16, 17))
        self.lblScaleX.setObjectName(_fromUtf8("lblScaleX"))
        self.btnSubmit = QtGui.QPushButton(self.grpControls)
        self.btnSubmit.setGeometry(QtCore.QRect(0, 380, 99, 27))
        self.btnSubmit.setObjectName(_fromUtf8("btnSubmit"))
        self.lblLineWidth = QtGui.QLabel(self.grpControls)
        self.lblLineWidth.setGeometry(QtCore.QRect(10, 270, 81, 17))
        self.lblLineWidth.setObjectName(_fromUtf8("lblLineWidth"))
        self.txtLineWidth = QtGui.QLineEdit(self.grpControls)
        self.txtLineWidth.setGeometry(QtCore.QRect(90, 270, 41, 27))
        self.txtLineWidth.setObjectName(_fromUtf8("txtLineWidth"))
        self.lblLineColor = QtGui.QLabel(self.grpControls)
        self.lblLineColor.setGeometry(QtCore.QRect(10, 310, 81, 17))
        self.lblLineColor.setObjectName(_fromUtf8("lblLineColor"))
        self.cbColor = KColorCombo(self.grpControls)
        self.cbColor.setGeometry(QtCore.QRect(100, 310, 95, 27))
        self.cbColor.setColor(QtGui.QColor(255, 0, 0))
        self.cbColor.setObjectName(_fromUtf8("cbColor"))
        self.txtScaleHeight = QtGui.QLineEdit(self.grpControls)
        self.txtScaleHeight.setGeometry(QtCore.QRect(70, 110, 41, 27))
        self.txtScaleHeight.setObjectName(_fromUtf8("txtScaleHeight"))
        self.lblHeightCm = QtGui.QLabel(self.grpControls)
        self.lblHeightCm.setGeometry(QtCore.QRect(120, 70, 51, 17))
        self.lblHeightCm.setText(_fromUtf8(""))
        self.lblHeightCm.setObjectName(_fromUtf8("lblHeightCm"))
        self.lblWidthCm = QtGui.QLabel(self.grpControls)
        self.lblWidthCm.setGeometry(QtCore.QRect(10, 70, 51, 17))
        self.lblWidthCm.setText(_fromUtf8(""))
        self.lblWidthCm.setObjectName(_fromUtf8("lblWidthCm"))
        self.lblSizeXcm = QtGui.QLabel(self.grpControls)
        self.lblSizeXcm.setGeometry(QtCore.QRect(80, 70, 16, 17))
        self.lblSizeXcm.setObjectName(_fromUtf8("lblSizeXcm"))
        frmMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(frmMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        frmMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(frmMain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        frmMain.setStatusBar(self.statusbar)
        self.actionOpen_Image = QtGui.QAction(frmMain)
        self.actionOpen_Image.setObjectName(_fromUtf8("actionOpen_Image"))
        self.actionExit = QtGui.QAction(frmMain)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)
        frmMain.setTabOrder(self.txtScaleWidth, self.txtScaleHeight)
        frmMain.setTabOrder(self.txtScaleHeight, self.txtVertical)
        frmMain.setTabOrder(self.txtVertical, self.txtHorizontal)
        frmMain.setTabOrder(self.txtHorizontal, self.txtLineWidth)
        frmMain.setTabOrder(self.txtLineWidth, self.cbColor)
        frmMain.setTabOrder(self.cbColor, self.btnSubmit)
        frmMain.setTabOrder(self.btnSubmit, self.btnReset)
        frmMain.setTabOrder(self.btnReset, self.imgView)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(_translate("frmMain", "Image Splitter", None))
        self.grpControls.setTitle(_translate("frmMain", "Controls", None))
        self.lblScale.setText(_translate("frmMain", "Scale (cm x cm)", None))
        self.txtScaleWidth.setText(_translate("frmMain", "1", None))
        self.btnReset.setText(_translate("frmMain", "Reset", None))
        self.lblWidthLabel.setText(_translate("frmMain", "Width", None))
        self.lblHeightLabel.setText(_translate("frmMain", "Height", None))
        self.lblSizeXLabel.setText(_translate("frmMain", "X", None))
        self.lblSizeX.setText(_translate("frmMain", "X", None))
        self.lblVerticalLabel.setText(_translate("frmMain", "Vertical", None))
        self.lblSegmentXLabel.setText(_translate("frmMain", "X", None))
        self.lblHorizontalLabel.setText(_translate("frmMain", "Horizontal", None))
        self.lblSegmentsLabel.setText(_translate("frmMain", "Segments", None))
        self.txtVertical.setText(_translate("frmMain", "0", None))
        self.lblVertical.setText(_translate("frmMain", "Lines", None))
        self.txtHorizontal.setText(_translate("frmMain", "0", None))
        self.lblHorizontal.setText(_translate("frmMain", "Lines", None))
        self.lblScaleX.setText(_translate("frmMain", "x", None))
        self.btnSubmit.setText(_translate("frmMain", "Submit", None))
        self.lblLineWidth.setText(_translate("frmMain", "Line Width", None))
        self.txtLineWidth.setText(_translate("frmMain", "1", None))
        self.lblLineColor.setText(_translate("frmMain", "Line Color", None))
        self.txtScaleHeight.setText(_translate("frmMain", "1", None))
        self.lblSizeXcm.setText(_translate("frmMain", "X", None))
        self.menuFile.setTitle(_translate("frmMain", "File", None))
        self.actionOpen_Image.setText(_translate("frmMain", "Open Image", None))
        self.actionOpen_Image.setShortcut(_translate("frmMain", "Ctrl+O", None))
        self.actionExit.setText(_translate("frmMain", "Exit", None))
        self.actionExit.setShortcut(_translate("frmMain", "Ctrl+E", None))

from PyKDE4.kdeui import KColorCombo
